###############################################################################
#
# Copyright (c) 2018 SafeNet. All rights reserved.
#
# This file contains information that is proprietary to SafeNet and may not be
# distributed or copied without written consent from SafeNet.
#
###############################################################################

%:
	$(MAKE) -C fm $@
	#$(MAKE) -C host $@